/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.briannqc.mavenbom.app;

import com.briannqc.mavenbom.lib.FutureStub;

import java.util.concurrent.ExecutionException;

public class App {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        final var future = FutureStub.ofString("Hello Maven BOM");
        System.out.println(future.get());
    }
}
