/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.briannqc.mavenbom.lib;

import com.google.common.util.concurrent.Futures;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Future;

public class FutureStub {

    public static Future<String> ofString(String s) {
        doSomethingFunOnPurpose();
        return CompletableFuture.completedFuture(s);
    }

    private static void doSomethingFunOnPurpose() {
        Futures.immediateCheckedFuture(new Object());
    }
}
